# Generated by Django 4.2 on 2023-06-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('chapterIndex', models.CharField(max_length=50)),
                ('chapter', models.CharField(max_length=50)),
                ('keyPointIndex', models.CharField(max_length=50)),
                ('keyPoint', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('homework', models.TextField(null=True)),
                ('exam', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassDataRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('classTargetIndex', models.CharField(max_length=50)),
                ('homeworkRatio', models.CharField(max_length=50, null=True)),
                ('examRatio', models.CharField(max_length=50, null=True)),
                ('experienceRatio', models.CharField(max_length=50, null=True)),
                ('courseGoalAttainment', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('chapterIndex', models.CharField(max_length=50)),
                ('theoryHours', models.CharField(max_length=50)),
                ('practiceHours', models.CharField(max_length=50)),
                ('selfLearningHours', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('userAccount', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('classInfo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('className', models.CharField(max_length=50)),
                ('requestIndex', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseInFosterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('className', models.CharField(max_length=50)),
                ('courseCategory', models.CharField(max_length=50)),
                ('credits', models.CharField(max_length=50)),
                ('hours', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=50)),
                ('isRequired', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('pointIndex', models.CharField(max_length=50)),
                ('className', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CultivationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('index', models.CharField(max_length=50)),
                ('cultivationGoal', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FosterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('briefInfo', models.TextField()),
                ('subjectDescription', models.TextField()),
                ('evaluationMechanism', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GoalAndRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('index', models.CharField(max_length=50)),
                ('requestIndex', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GraduateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('requestIndex', models.CharField(max_length=50)),
                ('graduateRequest', models.CharField(max_length=50)),
                ('pointIndex', models.CharField(max_length=50)),
                ('indexPoint', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPointContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('pointIndex', models.CharField(max_length=50)),
                ('classTarget', models.CharField(max_length=50)),
                ('classTargetIndex', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPointResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=50, null=True)),
                ('pointIndex', models.CharField(max_length=50)),
                ('className', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userAccount', models.CharField(max_length=50, unique=True)),
                ('userPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
